export const GET_POST_LIST_PENDING = "GET_POST_LIST_PENDING";
export const GET_POST_LIST_SUCCESS = "GET_POST_LIST_SUCCESS";
export const GET_POST_LIST_ERROR = "GET_POST_LIST_ERROR";
export const ADD_POST_ITEM_PENDING = "ADD_POST_ITEM_PENDING";
export const ADD_POST_ITEM_SUCCESS = "ADD_POST_ITEM_SUCCESS";
export const ADD_POST_ITEM_ERROR = "ADD_POST_ITEM_ERROR";
export const EDIT_POST_ITEM_PENDING = "EDIT_POST_ITEM_PENDING";
export const EDIT_POST_ITEM_SUCCESS = "EDIT_POST_ITEM_SUCCESS";
export const EDIT_POST_ITEM_ERROR = "EDIT_POST_ITEM_ERROR";
export const DELETE_POST_ITEM_PENDING = "DELETE_POST_ITEM_PENDING";
export const DELETE_POST_ITEM_SUCCESS = "DELETE_POST_ITEM_SUCCESS";
export const DELETE_POST_ITEM_ERROR = "DELETE_POST_ITEM_ERROR";

export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
